# Get the box up and running. These tasks run before the box is configured
# or the project is cloned or built. All system dependencies should be
# installed here.

- name: ensure apt cache is updated
  apt: update_cache=yes cache_valid_time=3600

- name: ensure all packages are upgraded safely
  apt: upgrade=safe
  when: env != "development"

- name: add keys to apt
  apt_key: url={{item}} state=present
  with_items: apt_keys

- name: add docker keys to apt
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id="58118E89F3A912897C070ADBF76221572C52609D"

- name: add ppas to apt
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items: apt_ppas

- name: install apt packages
  apt:
    name: "{{item}}"
    state: latest
  with_items: apt_packages

- name: ensure the right linux-image-extra package is installed for docker
  shell: "apt-get install --yes linux-image-extra-$(uname -r)"
